### ISSUE TITLE
Droplet Create can't find server.id

### ISSUE THREAD

**Issue by engineerKev** [rmoriz/knife-digital_ocean#55]
I am running this command 
knife digital_ocean droplet create --server-name chef-basics \
                                                             --size 66 \
                                                             --location 3 \
                                                             --image 5141286 \
                                                             --ssh-keys XXXXX

Everything runs well up until it tries to find the server.id value. When it does the config breaks and it throws this error. 

/Users/kevinruiz/.rvm/gems/ruby-2.1.2/gems/knife-digital_ocean-2.3.0/lib/chef/knife/digital_ocean_droplet_create.rb:211:in `run': undefined method `id' for #<String:0x007fe422354b58> (NoMethodError)
	from /Users/kevinruiz/.rvm/gems/ruby-2.1.2/gems/chef-12.0.0/lib/chef/knife.rb:417:in `block in run_with_pretty_exceptions'
	from /Users/kevinruiz/.rvm/gems/ruby-2.1.2/gems/chef-12.0.0/lib/chef/local_mode.rb:38:in `with_server_connectivity'
	from /Users/kevinruiz/.rvm/gems/ruby-2.1.2/gems/chef-12.0.0/lib/chef/knife.rb:416:in `run_with_pretty_exceptions'
	from /Users/kevinruiz/.rvm/gems/ruby-2.1.2/gems/chef-12.0.0/lib/chef/knife.rb:213:in `run'
	from /Users/kevinruiz/.rvm/gems/ruby-2.1.2/gems/chef-12.0.0/lib/chef/application/knife.rb:139:in `run'
	from /Users/kevinruiz/.rvm/gems/ruby-2.1.2/gems/chef-12.0.0/bin/knife:25:in `<top (required)>'
	from /Users/kevinruiz/.rvm/gems/ruby-2.1.2/bin/knife:23:in `load'
	from /Users/kevinruiz/.rvm/gems/ruby-2.1.2/bin/knife:23:in `<main>'
	from /Users/kevinruiz/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/kevinruiz/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'

Am I missing a key configuration step on the digital ocean end of things? Or am I just misusing the plugin? Thanks for the help. Really want to know what is wrong and how to fix it so I may move forward.

**Comment by gregf** [comment]
@engineerKev sorry to bug you, but did you ever get around to trying this again?

**Comment by engineerKev** [comment]
I had completely, forgotten I had replied. I am sorry to have kept you waiting for so long. I will try sometime this week(I know I keep saying that, again so sorry). Work has kept me busy and I haven't been able to revisit old projects and issues

**Comment by mccoold** [comment]
using the slug, not helping

**Comment by gregf** [comment]
@mccoold can you paste what you tried here?

**Comment by gregf** [comment]
I haven't heard anything about this in a while. It seems to be working just fine for others. If it's still a problem feel free to reopen the issue.
