### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by pkorsukov** [rmoriz/knife-digital_ocean#57]
I am trying to create a droplet using "knife digital_ocean droplet create" command.
On my DEV environment everything is working fine. On UAT server I am receiving the error:
Faraday::SSLError: SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A

It looks like an untrusted certificate problem. I am wondering if it is related to the most recent configuration of CloudFlare in DigitalOcean.
Any thoughts?

**Comment by rmoriz** [comment]
another approach:

start ```irb``` and get the default config directory of your openssl config:

```
require 'openssl'
File.dirname OpenSSL::Config::DEFAULT_CONFIG_FILE
```


then just place your cert.pem in that directory. Ruby's OpenSSL will automatically pick it up, and afaik faraday, too.

**Comment by gregf** [comment]
Was there a solution found here? It would be nice to document it in the readme if so.

**Comment by pkorsukov** [comment]
@rmoriz the result of your program is:
C:/Users/Luis/Code/luislavena/knap-build/var/knapsack/software/x86-windows/openssl/1.0.0n/ssl
It is obvious that I have no this catalog on the machine. So, you recon I should create it?

@gregf as I mentioned before I was able to solve the issue as described in my comment. So, it is good enough for me. Thanks!

**Comment by rmoriz** [comment]
@pkorsukov Hm, in this case you are out of luck. Looks like the variable is defined at build-time (c preprocessor) and that's the path on Luis system (Ruby for Windows maintainer).

https://github.com/openssl/openssl/blob/master/crypto/cryptlib.h#L85

So you'll stick with your solution to explicitly modyfing the OpenSSL::SSL::SSLContext from Ruby.

IMHO droplet_kit needs to expose the faraday option hash, so this gem could provide a method to set it directlly. See https://github.com/lostisland/faraday/wiki/Setting-up-SSL-certificates

**Comment by pkorsukov** [comment]
Ok, thank you. I can live with that workaround.
