### ISSUE TITLE
Ruby Issue for Fresh Installs

### ISSUE THREAD

**Issue by mccoold** [rmoriz/knife-digital_ocean#59]
This Gem is dependent on resource_kit and droplet_kit both have requirements of Ruby 2.0 or above.  Chef ships with Ruby 1.9 embedded. 

[root@workstation2 bin]# ./gem install knife-digital_ocean
Fetching: thread_safe-0.3.4.gem (100%)
Fetching: descendants_tracker-0.0.4.gem (100%)
Fetching: equalizer-0.0.9.gem (100%)
Fetching: coercible-1.0.0.gem (100%)
Fetching: ice_nine-0.11.1.gem (100%)
Fetching: axiom-types-0.1.1.gem (100%)
Fetching: virtus-1.0.3.gem (100%)
Fetching: resource_kit-0.1.1.gem (100%)
ERROR: Error installing knife-digital_ocean:
resource_kit requires Ruby version >= 2.0.

Thoughts?

**Comment by rmoriz** [comment]
Omnibus Chef-Client? Or ChefDK? Which version are you using?

**Comment by mccoold** [comment]
chef client, tested this on Window's (just because) but the real issue is CentOS 7  Chef version is 11.12

**Comment by rmoriz** [comment]
Chef 12 Omnibus comes with Ruby 2 so either you upgrade or ask DigitalOcean about supporting Ruby 1.9.3

**Comment by mccoold** [comment]
Opened a ticket with Digitial Ocean first, they said they do not support the Gem's and pointed me to you.  I was hoping to avoid upgrading to Chef 12, as that comes with its own challenges, but will look more into that now

**Comment by rmoriz** [comment]
You can try an older version of this gem that is not dependent to DigitalOceans heavily overengineered own gem

**Comment by mccoold** [comment]
FYI,

Chef 12 with Ruby 2 allowed the gem to install, I had to install faraday gem for the list function to work.  The droplet create is still throwing errors but I am still troubleshooting that.  Thanks for the help.  Also most of the documentation on the web to use this leverages their old API, to

**Comment by gregf** [comment]
@mccoold the faraday issue is a upstream issue with droplet_kit, I'm waiting on a new release. The only official documentation is in the readme, which should all be up to date. Let me know if you have found otherwise.

**Comment by rmoriz** [comment]
see https://github.com/rmoriz/knife-digital_ocean/issues/60
