### ISSUE TITLE
Faraday Dependency Missing

### ISSUE THREAD

**Issue by unixninja92** [rmoriz/knife-digital_ocean#60]
I just did a gem install of knife-digital_ocean on OSX and whenever I tried to run and digital ocean commands I'd get the following error:
`ERROR: LoadError: cannot load such file -- faraday`
Calling gem install faraday fixed this.

**Comment by rmoriz** [comment]
upstream bug, please report https://github.com/digitalocean/droplet_kit

**Comment by bobbytables** [comment]
Yup. I'm pushing the fix to rubygems right now. Sorry everyone for this inconvenience.

**Comment by bobbytables** [comment]
@rmoriz - I just pushed DropletKit 1.1.3 that includes the faraday dependency. Sorry about that.
