### ISSUE TITLE
knife digital_ocean image list --public command is broken

### ISSUE THREAD

**Issue by unixninja92** [rmoriz/knife-digital_ocean#61]
When I call `knife digital_ocean image list --public` I get the following error: 
`ERROR: ArgumentError: comparison of NilClass with String failed`

**Comment by jrmyward** [comment]
Same here.

**Comment by hhff** [comment]
Can we get a new release?  Just hit this bug

**Comment by gregf** [comment]
@hhff Done, thanks for the reminder.

**Comment by hhff** [comment]
thankyou @gregf !!
