### ISSUE TITLE
droplet create is failing 

### ISSUE THREAD

**Issue by mccoold** [rmoriz/knife-digital_ocean#62]
I keep getting this error
[root@dockertest1 knife]# knife digital_ocean droplet create --server-name test2 --image 9882330 --location 3 -S 63 --ssh-keys 611762 --bootstrap -VV
INFO: Using configuration from /root/.chef/knife.rb
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/knife-digital_ocean-2.3.0/lib/chef/knife/digital_ocean_droplet_create.rb:211:in `run': undefined method `id' for #<String:0x00000003abd648> (NoMethodError)
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/knife.rb:417:in `block in run_with_pretty_exceptions'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/local_mode.rb:38:in `with_server_connectivity'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/knife.rb:416:in `run_with_pretty_exceptions'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/knife.rb:213:in `run'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/application/knife.rb:139:in `run'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.0.3/bin/knife:25:in `<top (required)>'
        from /opt/chef/embedded/bin/knife:23:in `load'
        from /opt/chef/embedded/bin/knife:23:in `<main>'

by the way region list and size list does not return an ID anymore, it returns the Slug

**Comment by mccoold** [comment]
updated line 203 removing the splitting,

ssh_keys: locate_config_value(:ssh_key_ids),

did not resolve
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/knife-digital_ocean-2.3.0/lib/chef/knife/digital_ocean_droplet_create.rb:212:in `run': undefined met
hod `id' for #<String:0x413f058> (NoMethodError)
        from C:/opscode/chef/embedded/apps/chef/lib/chef/knife.rb:417:in `block in run_with_pretty_exceptions'
        from C:/opscode/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
        from C:/opscode/chef/embedded/apps/chef/lib/chef/knife.rb:416:in `run_with_pretty_exceptions'
        from C:/opscode/chef/embedded/apps/chef/lib/chef/knife.rb:213:in `run'
        from C:/opscode/chef/embedded/apps/chef/lib/chef/application/knife.rb:139:in `run'
        from C:/opscode/chef/embedded/apps/chef/bin/knife:25:in `<top (required)>'
        from C:/opscode/chef/bin/knife:52:in `load'
        from C:/opscode/chef/bin/knife:52:in `<main>'

**Comment by mccoold** [comment]
c:\opscode\chef\embedded\bin>knife digital_ocean droplet create --server-name test2 --image 9882330 --location nyc3 --size 2gb --ssh-keys 611762  --bo
otstrap --run-list "nodes_run_list" -VV

I am running Chef 12.03, I found some documentation that mentioned that .id is deprecated in Ruby 2 and above, investigating a little now

**Comment by gregf** [comment]
I just tried this and it works fine here. You might have got bit by a bug with --ssh-keys being split twice. It's since been patched, can you update to the latest gem release and try again? Thanks.

**Comment by gregf** [comment]
It's been a while without a response, so I am going to close this out. If it's still a issue for you with the latest release please reopen the issue.

**Comment by yarivdev** [comment]
this is still going on..

**Comment by gregf** [comment]
@yarivdev care to share the command you ran and the error output?

**Comment by yarivdev** [comment]
Sure, here's a couple: (erb)
this one used to work for a long time, not sure what i changed that now it's broken:
```
"knife digital_ocean droplet create -V --bootstrap -r recipe[base],recipe[ruby],recipe[pricer] -N #{Time.now.to_i} -K 722214 -I 9801950 -S 1gb -L ams2"
```

following the thread here, i also tried:
```
"knife digital_ocean droplet create -r 'recipe[chef-server]' -N 'chef.visualopt.com' -K yeah  -I ubuntu-14-04-x64 -S 2gb -L ams2 --solo -VV"
```
result is always the same:
```
/Users/yarivmathov/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/knife-digital_ocean-2.3.2/lib/chef/knife/digital_ocean_droplet_create.rb:211:in `run': undefined method `id' for #<String:0x007fc984bd7810> (NoMethodError)
	from /Users/yarivmathov/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-12.2.1/lib/chef/knife.rb:419:in `block in run_with_pretty_exceptions'
	from /Users/yarivmathov/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-12.2.1/lib/chef/local_mode.rb:38:in `with_server_connectivity'
	from /Users/yarivmathov/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-12.2.1/lib/chef/knife.rb:418:in `run_with_pretty_exceptions'
	from /Users/yarivmathov/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-12.2.1/lib/chef/knife.rb:214:in `run'
	from /Users/yarivmathov/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-12.2.1/lib/chef/application/knife.rb:138:in `run'
	from /Users/yarivmathov/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-12.2.1/bin/knife:25:in `<top (required)>'
	from /Users/yarivmathov/.rbenv/versions/2.1.5/bin/knife:23:in `load'
	from /Users/yarivmathov/.rbenv/versions/2.1.5/bin/knife:23:in `<main>'
```

**Comment by gregf** [comment]
Working fine here, are you running the latest version? Are you sure your oauth tokens are setup correctly?

```
knife digital_ocean droplet create -V --bootstrap -r recipe[apt] -N 04102015 -K 42795 -I 9801950 -S 1gb -L ams2
INFO: Using configuration from /home/gregf/.chef/knife.rb
Droplet creation for 04102015 started. Droplet-ID is 4814682
Waiting for IPv4-Address.done
IPv4 address is: 80.240.143.171
Waiting for sshd:
```

**Comment by yarivdev** [comment]
So i haven't noticed a billing issue on digitalocean, and they blocked me from creating droplets. this is probably it..
I'll confirm that it works once digital ocean restores my account.
As for the 2.3.2/2.3.3, i've tried both.

Sorry... :)
(perhaps more helpful error messages?)

**Comment by gregf** [comment]
Sadly the way with droplet_kit works theres no good way to return errors right now, It's something I'm working on having fixed though.

**Comment by yarivdev** [comment]
@gregf everything works just fine.
Thank you very much!
