### ISSUE TITLE
Droplet create failure

### ISSUE THREAD

**Issue by pkorsukov** [rmoriz/knife-digital_ocean#63]
I am receiving the error from digital_ocean plugin:
ERROR: DropletKit::FailedCreate: ["643099"] are invalid key identifiers for Droplet creation.

The POST command using curl is working fine. Knife plugin worked fine during the last month. So, it looks like some recent changes in API which cause the problem.

**Comment by pkorsukov** [comment]
After some research I have found that DO have changed the behavior of ssh_keys parameter in droplet creation API. It looks like it is not accepting a single element array anymore. So, I have tweaked the line 203 in digital_ocean_droplet_create.rb to
```ruby
ssh_keys: locate_config_value(:ssh_key_ids),#.split(/, ?/),
```
The proposed fix is not a fix, but it is working for my case. It looks like DO do not care too much regarding the stability of API.

**Comment by pkorsukov** [comment]
It looks like the issue appeared after the recent release https://developers.digitalocean.com/changelog/api-v2/new-droplet-create-validations/ so it may be related to String -> Int conversion in DO API

**Comment by phillbaker** [comment]
Hi @pkorsukov, I can't replicate this via curl, string and non-string ssh key ids work:

```
curl -X POST "https://api.digitalocean.com/v2/droplets" -d '{"name":"e11","region":"ams3","size":"2gb","image":"ubuntu-14-04-x64","ssh_keys":['244443']}' -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json"

curl -X POST "https://api.digitalocean.com/v2/droplets" -d '{"name":"e11","region":"ams3","size":"2gb","image":"ubuntu-14-04-x64","ssh_keys":[244443]}' -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" 
```

Can you provide a simple test case. We do strive to maintain API compatibility, however, API v2 is still in beta, so we're working out the kinks.

**Comment by phillbaker** [comment]
@pkorsukov after looking at the logs, this is what we've received:
```
status=422 "ssh_keys"=>[["643099"]]
status=202 "ssh_keys"=>[643099]
status=422 "ssh_keys"=>[["643099"]]
status=422 "ssh_keys"=>[["643099"]]
status=422 "ssh_keys"=>[["643099"]]
status=422 "ssh_keys"=>[["643099"]]
status=422 "ssh_keys"=>[["643099"]]
status=422 "ssh_keys"=>[["643099"]]
status=422 "ssh_keys"=>[["643099"]]
status=422 "ssh_keys"=>[["{643099}"]]
status=422 "ssh_keys"=>[["643099"]]
status=202 "ssh_keys"=>["643099"]
```

It appears that this validation is functioning - the key ids are wrapped in an extra array.

**Comment by pkorsukov** [comment]
@phillbaker it is defenettely a problem of knife-digital_ocean gem. I assume that versions 2.3.0 and 2.3.1 are affected. So, it is not related to the DropletKit.
It looks like in file digital_ocean_droplet_create.rb the line 
```ruby
ssh_keys: locate_config_value(:ssh_key_ids).split(/, ?/),
```
produces and array inside the array. I am calling it as
```cmd
knife digital_ocean ... --ssh-keys 643099
```

In your log the last row shows the request after I made a fix on the above line. And the second line shows my attempt via curl.

**Comment by la521o** [comment]
Having same issue here

**Comment by gregf** [comment]
This was fixed thanks to @mikian. Update your gems.
