### ISSUE TITLE
Kartograph 0.2.1 bug

### ISSUE THREAD

**Issue by joost** [rmoriz/knife-digital_ocean#68]
Downgrade to 0.2.0 solved the issue. Not sure if kartograph or knife-digital_ocean bug.

When doing `knife digital_ocean sshkey list` I got an error:

    vendor/bundle/gems/kartograph-0.2.1/lib/kartograph/map.rb:14:in `property': undefined method `+' for :read:Symbol (NoMethodError)
    from vendor/bundle/gems/droplet_kit-1.1.3/lib/droplet_kit/mappings/ssh_key_mapping.rb:9:in `block in <class:SSHKeyMapping>'
    from vendor/bundle/gems/kartograph-0.2.1/lib/kartograph/dsl.rb:12:in `instance_eval'

**Comment by gregf** [comment]
This is fixed in master, I'll be cutting a release within the hour.
