### ISSUE TITLE
FATAL: Cannot find sub command for: 'digital_ocean droplet list'

### ISSUE THREAD

**Issue by mehmetdavut** [rmoriz/knife-digital_ocean#71]
Hi,

When I try to use knife-digital_ocean gem, I am getting this error.

I see it at gem list --local:
knife-digital_ocean (2.3.3)

But it can't find digital ocean sub command.

**Comment by rmoriz** [comment]
chefdk user?

try `chef gem install knife-digital_ocean`

**Comment by mehmetdavut** [comment]
It works great :+1: Thank you
