### ISSUE TITLE
Domain record create doc wrong about type name?

### ISSUE THREAD

**Issue by Cervator** [rmoriz/knife-digital_ocean#78]
If I use the example in the doc:

`knife digital_ocean domain record create -D example.com -T cname -N www -a @`

Tweaked to fit an existing domain on my account I get the following: `ERROR: Record type is not included in the list`

Which seems to relate to "cname" not being an acceptable record type. Maybe it changed in the API at some point?

"aname" doesn't work either, but "A" does so the following command works fine:

```
C:\opscode\chef-repo>knife digital_ocean domain record create -D cmdbee.com -T A -N testsub -a 123.123.123.123
OK
```

Plain "C" doesn't work, but there's probably a list somewhere. Would be nice if the API returned the record type you attempted to use to make it more obvious what the problem actually is, but I am guessing that is DO-side :-)

**Comment by rmoriz** [comment]
how about `CNAME`?

**Comment by Cervator** [comment]
Yep that did it! Thanks :-)
