### ISSUE TITLE
block storage api

### ISSUE THREAD

**Issue by jjdevbiz** [rmoriz/knife-digital_ocean#86]
https://developers.digitalocean.com/documentation/v2/block-storage-beta/

Woohoooooo!!!

https://developers.digitalocean.com/documentation/v2/#block-storage
https://developers.digitalocean.com/documentation/v2/#block-storage-actions

Its out of beta and official: https://www.digitalocean.com/features/storage/

But who's going to integrate it into this gem??

**Comment by rmoriz** [comment]
If you are an DO employee, please don't spam OSS projects with "suggestions" to implement your product. If not, please provide PRs with code and tests.

**Comment by jjdevbiz** [comment]
I'm not a DO employee, but I am shamefully pushing for code to be written that I don't necessarily want to write! Yes, I apologize.
